name: ci

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILDKIT: 1

jobs:
  release:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: fregante/release-with-changelog@v3
        name: Create Release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-template: '- {title} ← {hash}'
          template: |
            ### Container image

            ```
            dummy release
            ```

            ### Changelog

            {commits}
