on:
  pull_request:
    branches:    
      - main
  release:

jobs:
  build-conda-packages:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Dummy release build
        shell: bash -l {0}
        run: |
          export GIT_DESCRIBE_TAG="${GITHUB_REF##*/}"
          echo "The githubtag: ${GIT_DESCRIBE_TAG}"
