name: pr

on:
  pull_request:
    branches: [ main ]

env:
  DOCKER_BUILDKIT: 1

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Dummy
        shell: bash -l {0}
        run: |
          echo "Dummy PR check"
 